Fix reading .bowerrc when it doesn't exist
If no .bowerrc file exists in the root-directory then bowercopy fails with the following error:
>Loading "bowercopy.js" tasks...ERROR
>Error: Unable to read ".bowerrc" file (Error code: ENOENT).
Checking if the file exists before reading it should fix the task from crashing. See #39